//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.StudentOfClassses = new HashSet<StudentOfClasss>();
        }
    
        public int ID { get; set; }
        public string MaClass { get; set; }
        public string NameClass { get; set; }
        public int TeacherID { get; set; }
        public Nullable<bool> Counts { get; set; }
        public Nullable<int> SoLuongHS { get; set; }
    
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentOfClasss> StudentOfClassses { get; set; }
    }
}
